# Configure this Discovery Server
eureka:
  instance:
    hostname: localhost
  client:  
    registerWithEureka: false
    fetchRegistry: false
     
server:
  port: 13001   # HTTP (Tomcat) port

# Discovery Server Dashboard uses FreeMarker.  
spring:
  thymeleaf:
    enabled: false     # Disable Thymeleaf 